version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "danieleschmidt"
    assignees:
      - "danieleschmidt"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "danieleschmidt"
    assignees:
      - "danieleschmidt"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "danieleschmidt"
    assignees:
      - "danieleschmidt"
    commit-message:
      prefix: "docker"
      include: "scope"