apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-cache-pvc
  namespace: edge-tpu-benchmark
  labels:
    app.kubernetes.io/name: edge-tpu-v5-benchmark
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: edge-tpu-benchmark-suite
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results-storage-pvc
  namespace: edge-tpu-benchmark
  labels:
    app.kubernetes.io/name: edge-tpu-v5-benchmark
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: edge-tpu-benchmark-suite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard