apiVersion: v1
kind: Namespace
metadata:
  name: edge-tpu-quantum-benchmark
  labels:
    name: edge-tpu-quantum-benchmark
    environment: production
    quantum.terragon.com/enabled: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-benchmark-config
  namespace: edge-tpu-quantum-benchmark
data:
  config.yaml: |
    quantum:
      coherence_time: 100.0
      decoherence_monitoring: true
      entanglement_enabled: true
      superposition_processing: true
    
    optimization:
      hyper_optimization: true
      bayesian_optimization: true
      quantum_annealing: true
      adaptive_scaling: true
    
    security:
      validation_level: "strict"
      error_recovery: true
      circuit_breakers: true
      
    monitoring:
      prometheus_enabled: true
      health_checks: true
      performance_tracking: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-benchmark-api
  namespace: edge-tpu-quantum-benchmark
  labels:
    app: quantum-benchmark-api
    version: v3.0
    tier: production
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: quantum-benchmark-api
  template:
    metadata:
      labels:
        app: quantum-benchmark-api
        version: v3.0
        quantum.terragon.com/enabled: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        quantum.terragon.com/coherence-time: "100"
        quantum.terragon.com/optimization-level: "hyper"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: quantum-benchmark-api
        image: ghcr.io/terragonlabs/edge-tpu-v5-benchmark:quantum-v3.0
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: grpc
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: QUANTUM_ENABLED
          value: "true"
        - name: OPTIMIZATION_LEVEL
          value: "hyper"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PROMETHEUS_PORT
          value: "9090"
        - name: CONFIG_FILE
          value: "/config/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
        - name: cache-volume
          mountPath: /cache
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            ephemeral-storage: "4Gi"
          limits:
            memory: "8Gi"
            cpu: "4000m"
            ephemeral-storage: "10Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /startup
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      volumes:
      - name: config-volume
        configMap:
          name: quantum-benchmark-config
      - name: tmp-volume
        emptyDir: {}
      - name: cache-volume
        emptyDir:
          sizeLimit: 5Gi
      nodeSelector:
        quantum.terragon.com/optimized: "true"
      tolerations:
      - key: "quantum.terragon.com/dedicated"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - quantum-benchmark-api
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: quantum-benchmark-service
  namespace: edge-tpu-quantum-benchmark
  labels:
    app: quantum-benchmark-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: grpc
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: quantum-benchmark-api

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quantum-benchmark-hpa
  namespace: edge-tpu-quantum-benchmark
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quantum-benchmark-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: quantum_coherence_level
      target:
        type: AverageValue
        averageValue: "0.8"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: quantum-benchmark-pdb
  namespace: edge-tpu-quantum-benchmark
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: quantum-benchmark-api

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quantum-benchmark-netpol
  namespace: edge-tpu-quantum-benchmark
spec:
  podSelector:
    matchLabels:
      app: quantum-benchmark-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 9090
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 9090

---
apiVersion: v1
kind: Secret
metadata:
  name: quantum-benchmark-secrets
  namespace: edge-tpu-quantum-benchmark
type: Opaque
data:
  # These would be base64 encoded in a real deployment
  api-key: ""  # Base64 encoded API key
  quantum-cert: ""  # Base64 encoded quantum certificate
  metrics-token: ""  # Base64 encoded metrics token